export const headersShown = [
  "Gene",
  "Nucleotide Change",
  "Protein Change",
  "Alias",
  "Region",
  "Last Evaluated",
  "Last Updated",
  "Reported Classification",
  "URL"
  // "Accession",
  // "Alt",
  // "Assembly",
  // "Chr",
  // "Genomic Start",
  // "Genomic Stop",
  // "Inferred Classification",
  // "Other Mappings",
  // "Ref",
  // "Reported Alt",
  // "Reported Ref",
  // "Source",
  // "Submitter Comment",
  // "Transcripts",
]